### ISSUE TITLE
No issue - just wanted to say thanks

### ISSUE THREAD

**Issue by dza6549** [gilescoope/rhubarb-timeline#1]
@gilescoope 

this is wonderful. I was just about to embark on building (very badly and with much anticipated sadness) a sprite lip sync solution for timeline. And you have made the perfect solution with Rhubarb *and* individual mouth shape clips!

thanks very much for releasing this! :)

Cheers

**Comment by gilescoope** [comment]
Thanks a lot, happy to save someone some time, and hope it works well for your project. I'd be interested to hear any further feedback as you use it more.

I'd just clarify for others reading this that I'm not the writer of Rhubarb itself, just this adapter and timeline tool.

**Comment by dza6549** [comment]
Yes Rhubarb is another project. Making a Unity timeline version is is not a task to be lightly dismissed. I'm now thinking about how to use your framework for a sprite based scenario. Heads, hair, eyes, clothes. 

If I earn a million dollars I shall return with thanks :)
