### ISSUE TITLE
its good but i dont know how to replicate the mouth movements ,, 

### ISSUE THREAD

**Issue by stickylabdev** [gilescoope/rhubarb-timeline#2]
what i want is someting really clear like this
![152150eb04723d1fb44203b8de189c7c](https://user-images.githubusercontent.com/13078369/113758731-757fac00-973e-11eb-8b1c-fa3897d31d3a.jpg)

the a till x ,, its non sense a should open mouth but in your sprite ,,its closed mouth ,so its makes me confused

**Comment by gilescoope** [comment]
Hi there, the A, B, C listed don't correspond to the sounds made by the letters 'A', 'B', 'C' when spoken. They are taken from the original rhubarb spec.

https://github.com/DanielSWolf/rhubarb-lip-sync

So in your image it is roughly:

D      F       C

E       B      H

F       A      G

Hope this makes sense.
